### PR TITLE
Remove pin on requests (fixes #41)

### LINKED ISSUE #41: Requests<2.30.0 has a security issue
### Current behavior

The current action depends on requests<2.30, but this causes the following:
```
❯ pip-audit
| Collecting inputs
Found 1 known vulnerability in 1 package
Name     Version ID                  Fix Versions
-------- ------- ------------------- ------------
requests 2.29.0  GHSA-j8r2-6x86-q33q 2.31.0
```
My project depends on requests 2.31.0, this issue is with the pinned version in this codebase.

I believe the reason why we were holding on the requests 2.30.0 issue is now fixed, so we should relax this condition.

### Expected behavior

I expected the action to not fail on its own.

### Steps to reproduce

1. Add pip-audit to an empty project
2. Run it.

### Relevant context

Nothing else needed.

### PR DESCRIPTION
**Pull request by Alexerson**
Pretty simple fix for #41 .

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @Alexerson!

Note the comment next to that pin: we can't _just_ remove this, because we have other subdependency constraints 🙂 

If you'd like to fully address this, you can update the `pip-audit` constraint from:

```
pip-audit ~= 2.0, >= 2.4.13
```

to:

```
pip-audit ~= 2.0, >= 2.5.6
```

...while also removing the `requests` pin. That will resolve the subdependency conflict (due to a release we made yesterday).

**Comment by Alexerson** [comment]
Ah, sorry you’re right. Pushing this in a sec.

**Comment by woodruffw** [comment]
Thank you! LGTM.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Thanks again! I'll push out a new version of this action momentarily.

**Pull request merged**
